bases:
- ../../base
- namespace.yaml

patchesStrategicMerge:
- replica-and-rollout-strategy.yaml
namespace: dev-namespace
commonLabels:
  env : dev

replicas:
- name: app1
  count: 3

images:
- name: nginx
  newName: nginx
  newTag: 1.19.0
  #  digest: sha256:24a0c4b4a4c0eb97a1aabb8e29f18e917d05abfe1b7a7c07857230879ce7d3d3
